<!-- Navigation -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container"> 
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed --> 
      <a class="navbar-brand" href="index">The Gong Lab</a> </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <a href="">Home</a> </li>
        <li> <a href="#home" class="dropdown-toggle" id="drop1" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Research <span class="caret"></span> </a>
          <ul class="dropdown-menu" aria-labelledby="drop1">
            <li><a href="research">Topic 1</a></li>
            <li><a href="research">Topic 2</a></li>
            <li><a href="research">Topic 3</a></li>
            <li><a href="research">Topic 4</a></li>
          </ul>
        </li>
        <li> <a href="publications">Publications</a> </li>
        <li> <a href="members">Members</a> </li>
      </ul>
    </div>
    <!-- /.navbar-collapse --> 
  </div>
  <!-- /.container --> 
</nav>